= DataVaccinator JavaScript Class API
:author: DataVaccinator Team
:email: info@datavaccinator.com
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== JavaScript Client API

The Client API is the interface that is provided by the DataVaccinator JavaScript API for client software developers.

Include the DataVaccinator JavaScript API and all needed classes into your existing application using this in the <head> section:

[source,html]
----
<!-- start vaccinator include -->
<script src="localforage.min.js"></script>
<script src="vaccinator_api.js"></script>
<!-- end vaccinator include -->
----

Now, there is a new class *Vaccinator* available.

Please note that the _localforage.min.js_ is for local database access and _vaccinator_api.js_ is the final class code you want to use.

All class functions except the <<validateAppId>> function are asynchronous and return a promise.

=== Initialization and configuration

The DataVaccinator class is named *Vaccinator* and in instantiated like this:

`variable = new Vaccinator(configurationObject);`

A typical instantiation with some configuration values looks like this:

[source,javascript]
----
try {
  const appId = 'someAppId'; // application password

  // initialize v as new DataVaccinator instance
  const v = new Vaccinator({
      serviceUrl: 'https://DataVaccinatorVaultURL',
      userIdentifier: 'username',
      password: 'password',
      appId: appId,
      headers: {'cache-control': 'max-age=60'},
      searchFields: [ "firstname", "lastname", "address_street" ],
  });

  // get some information from the server
  let serverInfo = await v.getServerInfo();
  console.log(serverInfo);

} catch (e) {
  // catch any vaccinator class errors from here. e is vaccinatorError class.
  console.error(e);
}
----

Don't forget to wrap a try/catch block around your class calls to handle potential errors thrown by the vaccinator class like in the above example.

This are the configuration options available:

serviceUrl:: serviceURl is the URL where the API endpoint at the service provider is located. For example: https://service-provider.tld/protocol. All POST calls of the API will be sent to this destination. Please note that "same origin" policy might affect this. In the best case, this is the same domain than your app is running at.

userIdentifier:: userIdentifier is some mandatory identifier that the class is using to handle different aspects of saving user related information (like app-id). Also, the class is submitting this information as uid parameter in all protocol calls to the service provider. We suggest to use the name of the user who is using your application (eg email address).

appId:: The app-id is the end users application password for additional encryption. The vaccinator class expects some app-id known. If not submitted or undefined, the class is trying to get it from previous calls (local database). It throws an error if this fails.

password:: This password is used to encrypt the app-id in the local storage database. If not submitted or undefined, the app-id will get stored without any encryption (not recommended). We recommend to submit the password the user entered for log-in to your application or some organization password. By this, the local database will not leak the app-id in case someone is trying to read the browser database.

useCache:: Set to false to disable any local caching. We suggest to not turn caching on/off during a working session.  Default is `true`.

debugMode:: Set debugMode to true in order to activate debug output to browser console. Mainly for finding bugs by the developer of DataVaccinator class but maybe also helpful for you. Default is 'false'.

 headers:: Define additional header values to send on service requests.

 searchFields:: Here you submit an array of field names to be used for search function. If your payload is JSON and contains values for the given fields, they will get uploaded as SearchHash to the DataVaccinator Vault. This then allows you to find the assigned VIDs later using the search function. To disable the feature, submit an empty array or no parameter.
 
 directLogin:: Enable direct login. By this, the protocol is enhanced by adding _sid_ and _spwd_ values (serviceProviderId and serviceProviderPwd). This is needed to directly access the DataVaccinator Vault without any intermediate or proxy instance. Submit like an object property of `{serviceProviderId:int, serviceProviderPwd:string}`.


=== new

[cols="1,4"]
|=======
|Description:
|Create a new PID entry.
|Parameters:
|(string) vaccinationData
|Return value:
|(promise) (string) VID
|Info:
|The *vaccinationData* is PID in some JSON encoded dataset. It may contain personal information of a person (PID). This is then returned later by the <<get>> function.
|=======

=== update

[cols="1,4"]
|=======
|Description:
|Update vaccinationData of an existing PID entry.
|Parameters:
|(string) VID, (string) vaccinationData
|Return value:
|(promise) (string) VID
|Info:
|The *VID* is the identifying Vaccination ID (for example, previously returned by <<new>>.

The *vaccinationData* is PID in some JSON encoded dataset. It may contain personal information of a person (PID).
|=======

=== get

[cols="1,4"]
|=======
|Description:
|Retrieve the vaccinationData of one or more given VID.
|Parameters:
|(array) multiple VIDs or (string) VID
|Return value:
|(promise) (object array) vaccinationData
|Info:
a|The submitted *VID* is the identifying Vaccination ID (previously returned by <<new>>). Multiple VIDs can be submitted as array with multiple VIDs or a string with multiple VIDs divided by blank. If you want to provide more than 500 VIDs, please call this
function in chunks (will trigger an exception otherwise).

The returned payload is an associative object array with the *VID* as key and some object as value. The value object is having two fields: *status* (OK or NOTFOUND) and *data* (the Vaccination Data). If *status* is NOTFOUND, data is false.

This is a typical object array response like displayed in Firefox console:

[source]
----
0d52f1b0a314fba7d45e87ca5bf5e654:
  Object { status: "OK",
           data: "{\"fn\":\"Spongebob\",\"ln\":\"Squarepants\"}"
         }
1d52f1b0a314fba7d45e87ca5bf5e654:
  Object { status: "NOTFOUND",
           data: false
         }
fb9a6fd4c504878b2a76d9e78af795bb:
  Object { status: "OK",
           data: "{\"fn\":\"Patrick\",\"ln\":\"Star\"}"
         }
----
Access the results like in this example:
[source,javascript]
----
var vid = '0d52f1b0a314fba7d45e87ca5bf5e654';
var status = result[vid]['status'];
----
|=======

=== delete

[cols="1,4"]
|=======
|Description:
|Delete the given entry.
|Parameters:
|(array) multiple VIDs or (string) VID
|Return value:
|(promise) (array) VID(s)
|Info:
|The *VID* is the identifying Vaccination ID (for example, returned by new). Multiple VIDs can be submitted as array with multiple VIDs or a string with multiple VIDs divided by blank.

If you want to provide more than 500 VIDs, please call this function in chunks (will trigger an exception otherwise).
|=======

=== wipe

[cols="1,4"]
|=======
|Description:
|Wipe the given PID entry from the local cache.

This does not delete data from DataVaccinator Vault!
|Parameters:
|(array) multiple VIDs or (string) VID
|Return value:
|(promise) (array) VID(s)
|Info:
|The *VID* is the identifying Vaccination ID (for example, returned by new). Multiple VIDs can be submitted as array with multiple VIDs or a string with multiple VIDs divided by blank.

Please note that, if the *VID* is requested after this was called, the system will request it again from the DataVaccinator Vault and will update the cache. A possible use case is, if you know that the local cache is outdated for this *VID*, you can force the system to refresh its cache by wiping the PID with this function.
|=======

=== wipeCache

[cols="1,4"]
|=======
|Description:
|Wipe all locally cached information.
|Parameters:
|(string) token (optional, unset or empty string to force wipe)
|Return value:
|(promise) (boolean) true = cache was wiped, false = cache stayed untouched
|Info:
a|This wipes all local cached information in case the given *token* (eg time stamp) is different to the one used before on this system, or it is unset or empty. If none of this applies, it does not wipe the local cache. There are two use-cases:

. If the service provider is sending a time stamp indicating last changes (refer to *update* vaccinator protocol function). In this case you may call <<wipeCache>> with the given time stamp as token. If the token differs from last time, this function will wipe the whole cache. New requests will restore the cache step by step. By this, your local cache is always up to date.
. If the application was used in Internet café or other security concerns are against permanent local caching (please note that the caching massively increases speed of the whole system). After the cache was wiped, all data has to become requested from the DataVaccinator Vault again if requested. Thus, please call this function (if needed) with no token regularly after logout (in this situation).
|=======

=== changeAppId

[cols="1,4"]
|=======
|Description:
|This is trying to re-encode all stored Vaccination Data (PID) after the app-id has changed.
|Parameters:
|(array) VIDs, (string) old app-id, (string) new app-id
|Return value:
|(promise) (int) number of processed items
|Info:
a|The app-id is used to encrypt the payload in identity management. For whatever reason, if the app-id is changing for a user, then all entries in identity management need to become re-encrypted. Obviously, this is not to be done on identity management place to protect the data. So it must be done locally.

For this, the API class downloads and decrypts all Vaccination Data. Then it logs out initializes again with the new app-id. Then, all Vaccination Data is getting encrypted and updated.

The function also updates the local cache. If you do not want all the data stay here, either use <<wipe>> to remove specific items or <<wipeCache>> to cleanup all cached items.

After the function ran, the *new app-id* is the current app-id and overlays the app-id given during initialization.

*VIDs* is one or more VIDs. Please submit as array. This list has to be complete! In doubt, make sure you have the list of ALL VIDs for this app-id.

*old app-id* and *new app-id* are the old and new app-id to use for re-encryption.

The whole process may take a long time, depending on the number of people affected. Until the promise is fulfilled you should show some "please wait" dialogue to tell the user that something is going on in the background.

|=======

CAUTION: It is important that this is called with ALL VIDs assigned to the given app-id. If not, some data in DataVaccinator Vault may stay encrypted with the old app-id. In the worst case, this would cause serious data loss!

NOTE: In case this function was interrupted, there is a chance that some entries in DataVaccinator Vault may be encrypted with the new app-id and other still with the old one. The API is making sure that only Vaccination Data encrypted with the old app-id get re-encrypted (by using the *cs* value from the payload). By this, it is possible to call this function multiple times (with exactly the same parameters) to fix any previous interruption.

=== getAppId

[cols="1,4"]
|=======
|Description:
|Returns the app-id that is currently in use.
|Parameters:
|-
|Return value:
|(promise) (string) app-id
|Info:
|If no app-id is available, it throws an error!
|=======

=== validateAppId

[cols="1,4"]
|=======
|Description:
|Validates the checksum of the given app-id.
|Parameters:
|(string) app-id
|Return value:
|(boolean) validity
|Info:
|Returns true if the given app-id contains a valid checksum. Returns false if not.
|=======

=== getServerInfo

[cols="1,4"]
|=======
|Description:
|Retrieves generic information from the connected DataVaccinator server.
|Parameters:
|-
|Return value:
|(promise) (array) server information.
|Info:
|The returned object array contains the following fields:

*status* The general state of this request ("OK", "INVALID" or "ERROR).

*version* The version of the DataVaccinator server.

*time* The current date and time on the DataVaccinator server.

*plugins* An array of plugins. Each entry has 'name', 'vendor' and 'license' field.

*uid* User ID submitted by the class during the call (you may ignore this).
|=======

== Search API

DataVaccinator offers you some sort of SSE (Searchable Symmetric Encryption) to allow you the search inside of PID/PII. By SSE, the DataVaccinator Vault is not storing unencrypted data while offering to search for it.

For further information, read link:https://github.com/Kukulkano/dv-vault/blob/master/docs/searchPlugin.adoc[the search documentation in dv-vault GitHub repository].

=== search

[cols="1,4"]
|=======
|Description:
|Search through the DataVaccinator Vault for entries.
|Parameters:
|(string) search term
|Return value:
|(promise) (array) VID(s)
|Info:
a|The search term is one or more words, divided by space. If multiple words are given, it will return only matches who matched both words in the payload (AND).

Search words do not have to be complete and case does not matter. The search always begins on the left and returns all matches there. Thus, you can simply enter "joh foo" to find John Foobar.
|=======

NOTE: This only works if the <<searchFields>> config parameter was set during class initialization. You can only search for entries that were pushed or updated with searchFields cnfiguration submitted.

NOTE: This only works if the DataVaccinator Vault activated the "search" plugin. If not, you will get EC_MISSING_PARAMETERS.

== Publishing API

The publishing API are additional functions for specific purpose. In distributed systems it may be needed to provide the payload to external parties. Think of health or police work, where sometimes datasets have to become exchanged in a way that person information has to be included. But even in such cases, the pseudonymisation should not become broken. Thus, the better way is to exchange pseudonymized datasets with VIDs and grant access to the PID/PII by the receiving party.

This is what the publishing functions allow you to do. Obviously, the receiving party should not know your app-id (password for your PID/PII) and therefore the publishing functions need a separate password provided for encryption. This is a new key you should share with the receiving party, together with the VID created.

[CAUTION]
====
*Published payloads have different behavior:*

. They have an expiration date (*durationDays*) which makes them become deleted automatically in DataVaccinator Vault if they expire.
. They can not get updated.
. They do not support <<search-api>> usage.
. They can get accessed by other service providers if they know the VID.
. They are encrypted with some different password than your common app-id.
. There is no caching for published stuff.
====

A typical process for exchanging pseudonymized information with DataVaccinator works like this:

. Make sure the receiving party is getting a login to your DataVaccinator instance:
.. They need their own *sid* and *spwd*.
.. Their system has to become whitelisted (IP whitelisting).
.. You may have to contact your DataVaccinator Vault provider to enable this (if you're not hosting the DataVaccinator Vault by yourself).
. Exchange a secure password for usage with DataVaccinator between you and the receiving party.
. Push the PID/PII datasets to exchange to DataVaccinator (using the <<publish>> function) and attach the resulting VIDs to your exchange data (payloads).
. Submit your exchange data to the receiving party.
. The receiving party uses its *sid*/*spwd* and the <<getPublished>> function to retrieve the PID/PII information if needed using your attached VIDs.


=== publish

[cols="1,4"]
|=======
|Description:
|Create a new PID entry for publishing.
|Parameters:
|(string) vaccinationData, (string) password, (int) durationDays
|Return value:
|(promise) (string) VID
|Info:
a|The *vaccinationData*, your PID information, is some JSON encoded dataset similar to the <<new>> function. It may contain personal information of a person. This is then returned later by <<getPublished>> function.

The *password* is a textual representation of a password used for encryption of the *vaccinationData* payload. We hash this with SHA256 for usage as encryption key, so you do not need to do that.

The *durationDays* are defining the expiration for this publishing. If the number of days is due, the DataVaccinator Vault will delete the entry automatically. Allowed values are between 1 and 365. Other values will trigger an error.

The publishing function asks for a password because it will use this to encrypt the payload. It is not using the provided app-id as password!

Refer to <<new>> function for further details.

|=======

=== getPublished

[cols="1,4"]
|=======
|Description:
|Retrieve published data from DataVaccinator Vault.
|Parameters:
|(array) multiple VIDs or (string) VID, (string) password
|Return value:
|(promise) (object array) vaccinationData
|Info:
a|The submitted **VID**s are the identifying Vaccination IDs, previously returned by <<publish>>. Multiple VIDs can be submitted as array with multiple VIDs or a string with multiple VIDs divided by blank. If you want to provide more than 500 VIDs, please call this
function in chunks (will trigger an exception otherwise).

The returned payload is an associative object array with the *VID* as key and some object as value. The value object is having two fields: *status* (OK or NOTFOUND) and *data* (the Vaccination Data). If *status* is NOTFOUND, data is false.

Refer to <<get>> function for further details on the returned format.
|=======

== Properties

There are a few public class properties that can be useful:

debugging:: If *true*, the debugging gets activated. With *false* it is deactivated. By this, you can turn on/off debugging messages at any time.

useCache:: Set to *false* directly after calling init() to disable any local caching. We suggest to not turn caching on/off during a working session. Instead, use it once after calling init() function.

appId:: Can get used to read the currently used App-ID. We suggest to not edit/write this value.

fromCache:: After you called the <<get>> function, this property contains an array with the vids that were retrieved from the local cache. If this counts 0 (empty array), all data was requested from the server. It allows you to verify cache usage.

== Error handling

The vaccinator class throws error of type *vaccinatorError* in case something goes wrong. The *vaccinatorError* inherits the JavaScript Error class and adds two additional values:

[cols="1,3"]
|=====
|reason:
a|It is one of the following reasons of the error:

. *VACCINATOR_SERVICE* +
The DataVaccinator Vault is the reason for the problem. Check vaccinatorCode value for more details.
. *VACCINATOR_INVALID* +
You very likely submitted some invalid or missing parameter. Not vaccinator related but related to your input.
. *VACCINATOR_UNKNOWN* +
Error with no further specification.

|vaccinatorCode:
|In case the reason was *VACCINATOR_SERVICE*, this code contains the return code from DataVaccinator Vault.
|=====

In general, if you get an error of reason *VACCINATOR_SERVICE*, you have to validate the vaccinatorCode and maybe inform the user about some issues that may go away in some time (try later).

If you get some *VACCINATOR_INVALID*, you very like passed in some parameter or values that do either not fit to the rules or are invalid or of wrong type.


== Migration from v1.x to v2.0

v2.0 is a major improvement of the origin vaccinator class.

create an instance with capital V: new Vaccinator();

The functions <<init>>, <<enableDirectLogin>>, <<setHeaders>>, <<enableSearchFunction>> were *removed* an the parameters moved into the constructor as one config parameter. You can use intellisense.

The function <<getAppId>> has now a "force" parameter.

The function <<validateAppId>> is now deprecated. Use the static method Vaccinator.validateAppId instead.

The property <<useCache>>, <<debugging>> is now private, because it can be set in the constructor.

The functions <<update>>, <<delete>>, <<wipe>> have no return value anymore. It had returned the same vid(s) only.

The legacy functions <<userNew>>, <<userUpdate>>, <<userDelete>>, <<userGet>> and <<userWipe>> removed.

The function <<get>> will now return a Map<string, VData>. Attention! Beside of the benefits of a Map, the Map values can not become accessed using the bracket notation "map['key']". It is neccessary to use the [Map.get] method or the [Map.size] instead of [length] property.

Because the <<validateAppId>> is now an async function, the app-Id can not be validated at the constructor anymore. Please check the app-Id with the [Vaccinator.validateAppId] function before passing it to the constructor!

The "aes.js" & "forge-sha256.min.js"-script is not necessary anymore and should be omitted in the html head declaration.

The constraint of max 500 vids per request for <<get>>, <<delete>> and <<getPublished>> is obsolete. Passed vids will become chunked now internaly to fit DataVaccinator vault constraints.
